# Generated by Django 4.2.30 on 2026-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='Link to buy this product on Amazon', max_length=500, null=True),
        ),
    ]
